### ISSUE TITLE
What is the easiest way to deploy Strapi next to Nuxt?

### ISSUE THREAD

**Issue by notflip** [nuxt-modules/strapi#302]
I haven't been able to find much examples of monorepos that have both Strapi and Nuxt,
What is the easiest way to deploy both and have them running alongside each other?

**Comment by SvenWesterlaken** [comment]
I use github actions and put both the strapi & nuxt on a droplet on digitalocean.

On the droplet I install:
- Node + PM2
- MySQL (& connect with MySQL workbench)
- nginx with reverse proxy

Then with the github actions I let it be deployed by creating a tar file, copying this to the server with ssh. Unpacking (& deleting it) on the server and next run it using pm2.

With nginx I reverse proxy strapi to `strapi.domain.com` and the nuxt app at `domain.com`. and auto renew https use let's encrypt.

If you would like I can share a version of my github action files.

**Comment by notflip** [comment]
@SvenWesterlaken I would love to see those! (dankjewel!)

**Comment by SvenWesterlaken** [comment]
Note that I have a combined repository with both nuxt & strapi in subdirectories. These should match the names of the working directories. Some GitHub actions don't use this working directory, therefore they first do a cd to the subfolder. If you have separate repositories for each then just remove the `cd` actions and the working directories and copy the separate jobs into their own repository.

My structure would look as follows:

```
.                                   # repository root directory
├── nuxt-frontend                   # Frontend Nuxt project
├── strapi-backend                  # Strapi backend project
└── .github/workflows               # Github actions folder
```

Lastly, don't forget to add your own needed environment variables & replace the URL domain. My choice for URLs is mostly:

- `https://strapi.<domain>.nl` for strapi
- `https://<domain>.nl` for nuxt frontend

**I use the following GitHub action workflow file:**

```yaml
name: build & deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  frontend:
    defaults:
      run:
        working-directory: nuxt-frontend
    name: build & deploy portal
    runs-on: ubuntu-latest
    steps:

    - name: checkout repository
      uses: actions/checkout@master

    - name: node setup
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: install packages
      run: npm install

    - name: build application
      run: npm run build
      env:
        STRAPI_URL: https://strapi.domain.nl
        BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}

    - name: make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_STRAPI_URL: https://strapi.domain.nl
        envkey_BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
        directory: nuxt-frontend
        file_name: .env

    - name: list files for checkup
      run: ls -a

    - name: create tar file
      run: tar --exclude 'node_modules' --exclude '.git' -vczf ../frontend.tar ./

    - name: copy tar via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "frontend.tar"
        target: "nuxt-frontend"

    - name: unzip tar remote & delete it
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd nuxt-frontend && tar -xvf frontend.tar && rm frontend.tar
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_KEY }}

    - name: install dependencies remote
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd nuxt-frontend && npm i
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_KEY }}

    - name: start nuxt remote
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd nuxt-frontend && pm2 start
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_KEY }}

# ----------------------
# Strapi
# ----------------------
  backend:
    defaults:
      run:
        working-directory: strapi-backend
    name: build & deploy strapi backend
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout repository
      uses: actions/checkout@master

    - name: node setup
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: install packages
      run: npm install

    - name: make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_NODE_ENV: production
        envkey_STRAPI_URL: https://strapi.domain.nl
        # envkey_ALLOW_ORIGINS: ${{ secrets.ENV_ALLOW_ORIGINS }}
        envkey_EMAIL_REPLY_TO: ${{ secrets.ENV_EMAIL_REPLY_TO }}
        envkey_EMAIL_FROM: ${{ secrets.ENV_EMAIL_FROM }}
        envkey_SMTP_HOST: ${{ secrets.ENV_SMTP_HOST}}
        envkey_SMTP_PORT: ${{ secrets.ENV_SMTP_PORT }}
        envkey_SMTP_USERNAME: ${{ secrets.ENV_SMTP_USERNAME }}
        envkey_SMTP_PASSWORD: ${{ secrets.ENV_SMTP_PASSWORD }}
        envkey_DATABASE_NAME: ${{ secrets.ENV_DATABASE_NAME }}
        envkey_DATABASE_USERNAME: ${{ secrets.ENV_DATABASE_USERNAME }}
        envkey_DATABASE_PASSWORD: ${{ secrets.ENV_DATABASE_PASSWORD }}
        envkey_JWT_SECRET: ${{ secrets.ENV_JWT_SECRET}}
        envkey_ADMIN_JWT_SECRET: ${{ secrets.ENV_ADMIN_JWT_SECRET}}
        envkey_API_TOKEN_SALT: ${{ secrets.ENV_API_TOKEN_SALT}}
        envkey_APP_KEYS: ${{ secrets.ENV_APP_KEYS }}
        envkey_URL: ${{ secrets.ENV_FRONTEND_URL }}
        directory: strapi-backend

    - name: build application
      run: npm run build
      env:
        NODE_ENV: production

    - name: list files for checkup
      run: ls -a

    - name: create tar file
      run: tar --exclude 'node_modules' --exclude '.git' -vczf ../strapi.tar ./

    - name: copy tar via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "strapi.tar"
        target: "strapi-backend"

    - name: unzip tar remote & delete it
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd strapi-backend && tar -xvf strapi.tar && rm strapi.tar
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_KEY }}

    - name: install dependencies remote
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd strapi-backend && npm i
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_KEY }}

    - name: start strapi remote
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd strapi-backend && pm2 start
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        privateKey: ${{ secrets.SSH_KEY }}

```
